# Generated by Django 5.1.3 on 2024-11-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0002_alter_favorite_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='types',
            field=models.CharField(blank=True, choices=[('144', '144'), ('360', '360'), ('480', '480'), ('720', '720'), ('1080', '1080')], default='360', max_length=10),
        ),
    ]
